'use strict';
/**
 * scripts/add_popularity.js
 * Adds a `popularity` integer (1-100) to every player in players.json.
 * Run:  node scripts/add_popularity.js
 *
 * Logic:
 *  1. Named overrides for every well-known player (curated by hand).
 *  2. For everyone else: stat-based formula using ppg as the main driver,
 *     with a small deterministic jitter so role-players aren't all identical.
 */
const fs   = require('fs');
const path = require('path');

const SRC  = path.join(__dirname, '..', 'players.json');
const db   = JSON.parse(fs.readFileSync(SRC, 'utf8'));

// ─── Curated overrides (name → popularity) ───────────────────────────────────
// Every household name is listed explicitly.  Unlisted players fall through
// to the formula.
const NAMED = {
  // ── All-time Icons (95-100) ──────────────────────────────────────────────
  'LeBron James':         100,
  'Michael Jordan':       100,
  'Kobe Bryant':          100,
  'Magic Johnson':        99,
  'Larry Bird':           96,
  'Kareem Abdul-Jabbar':  90,
  'Shaquille O\'Neal':    97,
  'Stephen Curry':        100,
  'Wilt Chamberlain':     92,
  'Bill Russell':         87,
  'Tim Duncan':           92,
  'Kevin Durant':         94,
  'Charles Barkley':      90,
  'Oscar Robertson':      89,
  'Jerry West':           97,
  'Hakeem Olajuwon':      93,
  'Julius Erving':        87,
  'Dirk Nowitzki':        96,
  'Giannis Antetokounmpo':95,

  // ── Superstars (85-94) ───────────────────────────────────────────────────
  'Dwyane Wade':          95,
  'Allen Iverson':        99,
  'Scottie Pippen':       94,
  'Patrick Ewing':        89,
  'Dominique Wilkins':    85,
  'Chris Paul':           96,
  'Russell Westbrook':    97,
  'James Harden':         83,
  'Kevin Garnett':        91,
  'Gary Payton':          90,
  'Karl Malone':          83,
  'John Stockton':        87,
  'Clyde Drexler':        87,
  'Isiah Thomas':         93,
  'David Robinson':       90,
  'Carmelo Anthony':      91,
  'Pau Gasol':            86,
  'Tracy McGrady':        89,
  'Vince Carter':         92,
  'Ray Allen':            88,
  'Paul Pierce':          89,
  'Reggie Miller':        87,
  'Kawhi Leonard':        85,
  'Anthony Davis':        89,
  'Nikola Jokic':         88,
  'Damian Lillard':       90,
  'Blake Griffin':        88,
  'Dwight Howard':        80,

  // ── Stars (75-84) ────────────────────────────────────────────────────────
  'Bob Cousy':            88,
  'Elgin Baylor':         85,
  'Walt Frazier':         80,
  'Dave Cowens':          74,
  'Bob McAdoo':           74,
  'Moses Malone':         80,
  'Adrian Dantley':       72,
  'Alex English':         72,
  'Nate Archibald':       76,
  'Bob Pettit':           78,
  'Elvin Hayes':          78,
  'Willis Reed':          78,
  'Dave DeBusschere':     72,
  'Bill Walton':          79,
  'Artis Gilmore':        72,
  'Dan Issel':            70,
  'George Gervin':        82,
  'David Thompson':       79,
  'Dennis Rodman':        95,
  'Mitch Richmond':       74,
  'Joe Dumars':           76,
  'Mark Price':           70,
  'Glen Rice':            69,
  'Alonzo Mourning':      78,
  'Dikembe Mutombo':      78,
  'Detlef Schrempf':      65,
  'Shawn Kemp':           78,
  'Gary Payton':          90,
  'Penny Hardaway':       84,
  'Grant Hill':           80,
  'Latrell Sprewell':     72,
  'Stephon Marbury':      74,
  'Jason Kidd':           85,
  'Steve Nash':           90,
  'Amar\'e Stoudemire':   76,
  'Shawn Marion':         70,
  'Leandro Barbosa':      58,
  'Yao Ming':             94,
  'Tony Parker':          85,
  'Manu Ginobili':        87,
  'Boris Diaw':           62,
  'Paul George':          89,
  'Kyrie Irving':         93,
  'Klay Thompson':        81,
  'Draymond Green':       78,
  'Kevin Love':           80,
  'DeMar DeRozan':        80,
  'Jimmy Butler':         94,
  'Joel Embiid':          68,
  'Jayson Tatum':         75,
  'Jaylen Brown':         81,
  'Luka Dončić':          94,
  'Luka Doncic':          94,
  'Devin Booker':         89,
  'Donovan Mitchell':     81,
  'Trae Young':           78,
  'Zion Williamson':      73,
  'De\'Aaron Fox':        78,
  'Karl-Anthony Towns':   78,
  'Rudy Gobert':          40,

  // ── Solid Contributors (65-74) ───────────────────────────────────────────
  'Sam Jones':            68,
  'John Havlicek':        80,
  'Tom Heinsohn':         62,
  'Tom Sanders':          55,
  'KC Jones':             60,
  'Frank Ramsey':         55,
  'Gail Goodrich':        66,
  'James Worthy':         80,
  'Byron Scott':          64,
  'Michael Cooper':       60,
  'A.C. Green':           60,
  'Robert Horry':         72,
  'Derek Fisher':         65,
  'Rick Fox':             60,
  'Brian Shaw':           55,
  'Devean George':        48,
  'Luke Walton':          52,
  'Vladimir Radmanovic':  48,
  'Sasha Vujacic':        50,
  'Jordan Farmar':        52,
  'Shannon Brown':        50,
  'Lamar Odom':           74,
  'Andrew Bynum':         62,
  'Pau Gasol':            86,
  'Ron Artest':           70,
  'Metta World Peace':    68,
  'Ron Harper':           62,
  'Bill Wennington':      45,
  'John Paxson':          62,
  'Horace Grant':         66,
  'B.J. Armstrong':       58,
  'Toni Kukoc':           72,
  'Luc Longley':          50,
  'Steve Kerr':           68,
  'Dennis Rodman':        95,
  'Jack Haley':           38,
  'Will Perdue':          40,
  'Stacey King':          42,
  'Craig Hodges':         52,
  'Bob Love':             62,
  'Norm Van Lier':        58,
  'Tom Boerwinkle':       46,
  'Chet Walker':          60,
  'Jerry Sloan':          64,
  'Bob Boozer':           52,
  'Guy Rodgers':          56,
  'Hal Greer':            64,
  'Luke Jackson':         48,
  'Chet Walker':          60,
  'Billy Cunningham':     68,
  'Hersey Hawkins':       60,
  'Jeff Hornacek':        64,
  'Dan Majerle':          62,
  'Kevin Johnson':        70,
  'Tom Chambers':         64,
  'Eddie Johnson':        56,
  'Mark West':            50,
  'Andrew Lang':          44,
  'Joe Klein':            40,
  'Jeff Hornacek':        64,
  'Danny Ainge':          65,
  'Kevin McHale':         80,
  'Robert Parish':        78,
  'Dennis Johnson':       68,
  'Cedric Maxwell':       62,
  'M.L. Carr':            50,
  'Gerald Henderson':     52,
  'Rick Robey':           44,
  'Scott Wedman':         52,
  'Bill Laimbeer':        72,
  'Vinnie Johnson':       62,
  'John Salley':          58,
  'James Edwards':        52,
  'Dennis Rodman':        84,
  'Mark Aguirre':         60,
  'Adrian Dantley':       72,
  'Spencer Haywood':      62,
  'Bob Lanier':           68,
  'Dave Bing':            68,
  'Terry Tyler':          45,
  'M.L. Carr':            50,
  'Bob Dandridge':        60,
  'Jon McGlocklin':       50,
  'Oscar Robertson':      93,
  'Bob Boozer':           52,
  'Flynn Robinson':       48,
  'Greg Smith':           42,
  'Kareem Abdul-Jabbar':  97,
  'Junior Bridgeman':     52,
  'Marques Johnson':      60,
  'Jon McGlocklin':       50,
  'Quinn Buckner':        52,
  'Harvey Catchings':     42,
  'Dave Meyers':          44,
  'Elmore Smith':         48,
  'Terry Cummings':       60,
  'Sidney Moncrief':      66,
  'Craig Hodges':         52,
  'Paul Pressey':         52,
  'Ricky Pierce':         58,
  'Jack Sikma':           62,
  'Fred Roberts':         40,
  'Randy Breuer':         42,
  'Larry Krystkowiak':    38,
  'Nate Archibald':       76,
  'Jo Jo White':          62,
  'Paul Silas':           58,
  'Don Nelson':           60,
  'Charlie Scott':        56,
  'Don Chaney':           50,
  'Tom Heinsohn':         62,
  'Rick Barry':           80,
  'Jamaal Wilkes':        64,
  'Luol Deng':            68,
  'Joakim Noah':          70,
  'Derrick Rose':         82,
  'Carlos Boozer':        64,
  'Richard Hamilton':     66,
  'Chauncey Billups':     76,
  'Tayshaun Prince':      64,
  'Rasheed Wallace':      70,
  'Ben Wallace':          72,
  'Lindsey Hunter':       52,
  'Elden Campbell':       52,
  'Eddie Jones':          60,
  'Nick Van Exel':        64,
  'Cedric Ceballos':      58,
  'Tony Battie':          46,
  'Derek Fisher':         65,
  'Tyronn Lue':           54,
  'Horace Grant':         66,
  'Brendan Haywood':      48,
  'DeShawn Stevenson':    50,
  'Jason Terry':          62,
  'Shawn Marion':         70,
  'Tyson Chandler':       60,
  'Caron Butler':         60,
  'Peja Stojakovic':      66,
  'Chris Webber':         76,
  'Vlade Divac':          66,
  'Jason Williams':       60,
  'Bobby Jackson':        52,
  'Mike Bibby':           60,
  'Brad Miller':          54,
  'Hedo Turkoglu':        60,
  'Rashard Lewis':        60,
  'Mickael Pietrus':      48,
  'Tony Battie':          46,
  'Grant Hill':           80,
  'Jameer Nelson':        56,
  'Dwight Howard':        84,
  'JJ Redick':            88,
  'Keyon Dooling':        44,
  'Tony Allen':           62,
  'Mike Miller':          56,
  'Shane Battier':        60,
  'Mario Chalmers':       56,
  'Udonis Haslem':        58,
  'Chris Bosh':           78,
  'Norris Cole':          44,
  'Joel Anthony':         42,
  'LeBron James':         100,
  'Dwyane Wade':          92,
  'Ray Allen':            85,
  'Rashard Lewis':        60,
  'Alonzo Mourning':      78,
  'Anderson Varejao':     54,
  'Mike Dunleavy Jr.':    50,
  'Brendan Haywood':      48,
  'Matthew Dellavedova':  52,
  'Tristan Thompson':     60,
  'J.R. Smith':           62,
  'Iman Shumpert':        54,
  'Kevin Love':           76,
  'Kyrie Irving':         88,
  'Richard Jefferson':    54,
  'Channing Frye':        50,
  'DeAndre Jordan':       62,
  'Blake Griffin':        83,
  'Chris Paul':           90,
  'Jamal Crawford':       62,
  'Mo Williams':          54,
  'Nick Young':           56,
  'Willie Green':         44,
  'Kenyon Martin':        60,
  'Carmelo Anthony':      86,
  'Chauncey Billups':     76,
  'Nene':                 52,
  'Marcus Camby':         62,
  'Kenyon Martin':        60,
  'Steve Blake':          46,
  'Rudy Fernandez':       52,
  'LaMarcus Aldridge':    72,
  'Damian Lillard':       84,
  'Nicolas Batum':        58,
  'Wesley Matthews':      54,
  'Robin Lopez':          52,
  'Meyers Leonard':       46,
  'Luke Ridnour':         46,
  'Raymond Felton':       52,
  'Enes Kanter':          54,
  'Andre Iguodala':       72,
  'Harrison Barnes':      60,
  'Shaun Livingston':     56,
  'Andrew Bogut':         58,
  'Festus Ezeli':         44,
  'Leandro Barbosa':      58,
  'Marreese Speights':    46,
  'David Lee':            56,
  'Ian Clark':            42,
  'Zaza Pachulia':        48,
  'JaVale McGee':         56,
  'Omri Casspi':          46,
  'Nick Young':           56,
  'Kevon Looney':         48,
  'Jonas Jerebko':        44,
  'Quinn Cook':           42,
  'Jordan Bell':          40,
  'Patrick McCaw':        46,
  'Klay Thompson':        86,
  'Draymond Green':       82,
  'Kevin Durant':         95,
  'DeMarcus Cousins':     72,
  'Tony Parker':          83,
  'Manu Ginobili':        84,
  'Tim Duncan':           95,
  'Kawhi Leonard':        85,
  'Danny Green':          58,
  'Patty Mills':          56,
  'Marco Belinelli':      54,
  'Matt Bonner':          48,
  'Tiago Splitter':       50,
  'Cory Joseph':          44,
  'Bryn Forbes':          44,
  'Kyle Anderson':        46,
  'Pau Gasol':            86,
  'David West':           58,
  'LaMarcus Aldridge':    72,
  'Rudy Gay':             62,
  'Jonathon Simmons':     46,
  'Dontae Jones':         36,
  'Bruce Bowen':          60,
  'Robert Horry':         72,
  'Speedy Claxton':       48,
  'Stephen Jackson':      56,
  'Brent Barry':          54,
  'Rasho Nesterovic':     48,
  'Devin Brown':          42,
  'Antonio Daniels':      46,
  'Avery Johnson':        58,
  'Jaren Jackson Sr.':    46,
  'Terry Porter':         56,
  'Reggie Johnson':       40,
  'Sidney Green':         42,
  'Craig Anderson':       40,
  'John Salley':          58,
  'Olden Polynice':       44,
  'Rony Seikaly':         50,
  'Sherman Douglas':      50,
  'Billy Owens':          52,
  'Harold Miner':         48,
  'Glen Rice':            69,
  'Steve Smith':          58,
  'Dan Majerle':          62,
  'P.J. Brown':           50,
  'Timmy Hardaway':       70,
  'Tim Hardaway':         70,
  'Jamal Mashburn':       60,
  'Isaac Austin':         42,
  'Rex Chapman':          54,
  'Voshon Lenard':        44,
  'Anthony Mason':        60,
  'Patrick Ewing':        90,
  'John Starks':          64,
  'Allan Houston':        62,
  'Charles Oakley':       60,
  'Larry Johnson':        64,
  'Charles Smith':        50,
  'Derek Harper':         56,
  'Anthony Bonner':       40,
  'Herb Williams':        48,
  'Hubert Davis':         48,
  'Charlie Ward':         46,
  'Chris Dudley':         42,
  'Marcus Camby':         62,
  'Latrell Sprewell':     72,
  'Chris Childs':         46,
  'Kurt Thomas':          50,
  'Clarence Weatherspoon':46,
  'Buck Williams':        56,
  'Pete Myers':           38,
  'Harold Ellis':         36,
  'Andrew Toney':         52,
  'Moses Malone':         80,
  'Charles Barkley':      94,
  'Julius Erving':        93,
  'Maurice Cheeks':       64,
  'Bobby Jones':          56,
  'Caldwell Jones':       50,
  'Daryl Dawkins':        58,
  'Lionel Hollins':       52,
  'Henry Bibby':          46,
  'Steve Mix':            42,
  'Doug Collins':         58,
  'World B. Free':        56,
  'Mike Dunleavy':        46,
  'Clemon Johnson':       38,
  'Mark McNamara':        36,
  'George McGinnis':      58,
  'Lloyd Free':           52,
  'Harvey Catchings':     42,
  'Terry Furlow':         40,
  'Wali Jones':           44,
  'Walt Bellamy':         58,
  'Jerry Lucas':          66,
  'Bill Bradley':         64,
  'Dave DeBusschere':     72,
  'Dick Barnett':         52,
  'Dick Van Arsdale':     54,
  'Cazzie Russell':       52,
  'Phil Jackson':         62,
  'Mike Riordan':         42,
  'Nate Bowman':          38,
  'Bill Hosket':          36,
  'Don May':              34,
  'Emmette Bryant':       38,
  'Dave Stallworth':      44,
  'Freddie Crawford':     38,
  'Len Wilkens':          64,
  'Lenny Wilkens':        64,
  'Bob Rule':             50,
  'Spencer Haywood':      62,
  'Gus Williams':         58,
  'Dennis Johnson':       68,
  'Jack Sikma':           62,
  'Fred Brown':           52,
  'Paul Silas':           58,
  'James Bailey':         40,
  'Phil Smith':           46,
  'Butch Lee':            38,
  'Marvin Webster':       44,
  'Downtown Freddie Brown': 52,
  'John Johnson':         50,
  'Tom LaGarde':          38,
  'Mike Green':           38,
  'Vinnie Johnson':       62,
  'Joe Barry Carroll':    52,
  'Bernard King':         70,
  'Ron Brewer':           46,
  'Jim McElroy':          36,
  'Lorenzo Romar':        40,
  'Phil Ford':            48,
  'Billy Paultz':         44,
  'Purvis Short':         52,
  'Sleepy Floyd':         56,
  'Chris Mullin':         72,
  'Tim Hardaway':         70,
  'Mitch Richmond':       74,
  'Rod Higgins':          44,
  'Tom Tolbert':          40,
  'Alton Lister':         42,
  'Jerome Whitehead':     36,
  'Larry Smith':          44,
  'Victor Alexander':     38,
  'Sarunas Marciulionis': 52,
  'Tyrone Hill':          46,
  'Billy Owens':          52,
  'Jeff Grayer':          40,
  'Bimbo Coles':          46,
  'Latrell Sprewell':     72,
  'B.J. Armstrong':       58,
  'Pete Chilcutt':        36,
  'Felton Spencer':       40,
  'Chris Gatling':        44,
  'Clifford Rozier':      36,
  'Donyell Marshall':     52,
  'Joe Smith':            54,
  'Bimbo Coles':          46,
  'Brian Shaw':           55,
  'Rick Adelman':         46,
  'John Starks':          64,
  'Anfernee Hardaway':    82,
  'Nick Anderson':        56,
  'Dennis Scott':         54,
  'Horace Grant':         66,
  'Brian Hill':           36,
  'Tree Rollins':         44,
  'Sam Vincent':          44,
  'Jerry Reynolds':       38,
  'Reggie Theus':         56,
  'Scott Skiles':         52,
  'Terry Catledge':       40,
  'Otis Smith':           42,
  'Mark Acres':           36,
  'Sidney Green':         42,
  'Michael Ansley':       34,
  'Jeff Turner':          38,
  'Morlon Wiley':         36,
  'Tyrone Corbin':        46,
  'Randy Wittman':        42,
  'Mark Davis':           36,
  'Jim Petersen':         38,
  'Brad Lohaus':          40,
  'Pooh Richardson':      46,
  'Gerald Glass':         42,
  'Isaiah Rider':         52,
  'Christian Laettner':   56,
  'Doug West':            46,
  'Thurl Bailey':         46,
  'Darrell Griffith':     54,
  'Jeff Malone':          56,
  'Mark Eaton':           56,
  'Blue Edwards':         44,
  'Walter Davis':         58,
  'Larry Nance':          56,
  'Xavier McDaniel':      56,
  'Dennis Awtrey':        36,
  'Neal Walk':            42,
  'Charlie Scott':        56,
  'Paul Westphal':        64,
  'Alvan Adams':          52,
  'Don Buse':             46,
  'Truck Robinson':       52,
  'Leonard Robinson':     44,
  'Ron Lee':              38,
  'Mike Bantom':          40,
  'Bayard Forrest':       34,
  'Johnny High':          36,
  'Joel Kramer':          34,
  'Rich Kelley':          40,
  'Kyle Macy':            44,
  'Jeff Cook':            36,
  'James Edwards':        52,
  'Walter Davis':         58,
  'Larry Nance':          56,
  'Mike Sanders':         40,
  'Jay Humphries':        44,
  'Winston Garland':      40,
  'Clifford Robinson':    56,
  'Terry Porter':         56,
  'Kevin Duckworth':      50,
  'Jerome Kersey':        52,
  'Sam Bowie':            50,
  'Mychal Thompson':      52,
  'Danny Young':          40,
  'Jim Paxson':           48,
  'Lafayette Lever':      54,
  'Bill Hanzlik':         40,
  'Wayne Cooper':         42,
  'Danny Schayes':        44,
  'Blair Rasmussen':      38,
  'Jay Vincent':          44,
  'T.R. Dunn':            40,
  'Keith Gray':           34,
};

// ─── Stat-based fallback ──────────────────────────────────────────────────────
function formulaPopularity(player) {
  // Base from scoring — most recognisable stat in the public eye
  const ppgBase = Math.min(player.ppg / 35, 1) * 55; // 35 ppg → 55 pts

  // Supporting stats add a little
  const supportBase =
    (player.apg / 12) * 8 +   // elite PG-level assists
    (player.rpg / 20) * 7 +   // elite rebounder
    (player.spg / 3)  * 5 +
    (player.bpg / 5)  * 5;

  const base = Math.round(ppgBase + supportBase);

  // Deterministic jitter from the player id so the same player always
  // gets the same score (no randomness).
  let hash = 0;
  for (let i = 0; i < (player.id || player.name).length; i++) {
    hash = ((hash << 5) - hash) + (player.id || player.name).charCodeAt(i);
    hash |= 0;
  }
  const jitter = Math.abs(hash % 11) - 5; // -5 … +5

  return Math.min(100, Math.max(35, base + jitter));
}

// ─── Apply ────────────────────────────────────────────────────────────────────
let total = 0, named = 0, formula = 0;

for (const key of Object.keys(db)) {
  for (const player of db[key]) {
    if (NAMED[player.name] !== undefined) {
      player.popularity = NAMED[player.name];
      named++;
    } else {
      player.popularity = formulaPopularity(player);
      formula++;
    }
    total++;
  }
}

fs.writeFileSync(SRC, JSON.stringify(db, null, 2), 'utf8');

console.log(`Done.`);
console.log(`  Total players     : ${total}`);
console.log(`  Named overrides   : ${named}`);
console.log(`  Formula-derived   : ${formula}`);
console.log(`Wrote ${SRC}`);
