'use strict';
/**
 * scripts/add_popularity.js
 * Adds a `popularity` integer (1-100) to every player in players.json.
 * Run:  node scripts/add_popularity.js
 *
 * Logic:
 *  1. Named overrides for every well-known player (curated by hand).
 *  2. For everyone else: stat-based formula using ppg as the main driver,
 *     with a small deterministic jitter so role-players aren't all identical.
 */
const fs   = require('fs');
const path = require('path');

const SRC  = path.join(__dirname, '..', 'players.json');
const db   = JSON.parse(fs.readFileSync(SRC, 'utf8'));

// ─── Curated overrides (name → popularity) ───────────────────────────────────
// Every household name is listed explicitly.  Unlisted players fall through
// to the formula.
const NAMED = {
  'Michael Jordan':          99,
  'LeBron James':            99,
  'Magic Johnson':           98,
  'Wilt Chamberlain':        92,
  'Bill Russell':            87,
  'Kareem Abdul-Jabbar':     90,
  'Kobe Bryant':             98,
  'Shaquille O\'Neal':       97,
  'Larry Bird':              96,
  'Jerry West':              93,
  'Giannis Antetokounmpo':   92,
  'Julius Erving':           92,
  'Stephen Curry':           98,
  'Tim Duncan':              92,
  'Charles Barkley':         91,
  'Kevin Durant':            91,
  'Dirk Nowitzki':           94,
  'Oscar Robertson':         90,
  'Allen Iverson':           98,
  'Carmelo Anthony':         88,
  'David Robinson':          88,
  'Dwyane Wade':             95,
  'Hakeem Olajuwon':         88,
  'Isiah Thomas':            94,
  'James Harden':            65,
  'Kevin Garnett':           88,
  'Luka Doncic':             92,
  'Nikola Jokic':            80,
  'Scottie Pippen':          92,
  'Kawhi Leonard':           80,
  'Dennis Rodman':           96,
  'George Gervin':           85,
  'Kyrie Irving':            85,
  'Moses Malone':            85,
  'Tracy McGrady':           84,
  'Anthony Davis':           80,
  'Bob Cousy':               82,
  'Damian Lillard':          89,
  'Dwight Howard':           75,
  'Elgin Baylor':            82,
  'Jayson Tatum':            75,
  'Joel Embiid':             65,
  'Karl Malone':             70,
  'Manu Ginobili':           82,
  'Pete Maravich':           82,
  'Ray Allen':               82,
  'Rick Barry':              82,
  'Russell Westbrook':       93,
  'Steve Nash':              82,
  'Yao Ming':                90,
  'Bill Walton':             80,
  'Patrick Ewing':           80,
  'Chris Paul':              78,
  'Clyde Drexler':           78,
  'Dikembe Mutombo':         78,
  'Gary Payton':             78,
  'Grant Hill':              78,
  'Jason Kidd':              78,
  'John Havlicek':           78,
  'John Stockton':           78,
  'Kevin McHale':            78,
  'Tony Parker':             78,
  'Victor Wembanyama':       88,
  'Walt Frazier':            78,
  'Chris Webber':            76,
  'Alonzo Mourning':         75,
  'David Thompson':          75,
  'Elvin Hayes':             75,
  'Jimmy Butler':            75,
  'Klay Thompson':           75,
  'Paul Pierce':             85,
  'Jaylen Brown':            74,
  'Pau Gasol':               74,
  'Amar\'e Stoudemire':      72,
  'Anfernee Hardaway':       72,
  'Artis Gilmore':           72,
  'Chris Bosh':              72,
  'Derrick Rose':            95,
  'Devin Booker':            72,
  'Donovan Mitchell':        72,
  'Draymond Green':          72,
  'James Worthy':            72,
  'Joe Dumars':              72,
  'Robert Parish':           72,
  'Shawn Kemp':              72,
  'Willis Reed':             72,
  'Chauncey Billups':        70,
  'Dave Cowens':             70,
  'Andre Iguodala':          68,
  'Ben Simmons':             68,
  'Ben Wallace':             68,
  'Bill Laimbeer':           68,
  'Billy Cunningham':        68,
  'Blake Griffin':           68,
  'Bob Lanier':              68,
  'Chris Mullin':            68,
  'Dan Issel':               68,
  'Deron Williams':          68,
  'Kevin Johnson':           68,
  'Kevin Love':              68,
  'Marc Gasol':              68,
  'Nate Thurmond':           68,
  'Rajon Rondo':             68,
  'Rudy Gobert':             68,
  'Shai Gilgeous-Alexander': 68,
  'Shawn Marion':            68,
  'Tim Hardaway':            68,
  'Rasheed Wallace':         67,
  'Jalen Brunson':           90,
  'Bam Adebayo':             65,
  'Baron Davis':             65,
  'Dave Bing':               65,
  'Dave DeBusschere':        65,
  'DeMar DeRozan':           65,
  'Earl Monroe':             65,
  'Gail Goodrich':           65,
  'Jamal Murray':            65,
  'Kyle Lowry':              65,
  'Peja Stojakovic':         65,
  'Zach LaVine':             65,
  'Andrei Kirilenko':        63,
  'Bob McAdoo':              63,
  'Connie Hawkins':          63,
  'DeMarcus Cousins':        63,
  'Jrue Holiday':            63,
  'LaMarcus Aldridge':       63,
  'Latrell Sprewell':        63,
  'Pascal Siakam':           63,
  'Richard Hamilton':        63,
  'Adrian Dantley':          62,
  'Al Horford':              62,
  'Alex English':            62,
  'Antoine Walker':          62,
  'Bernard King':            62,
  'Bradley Beal':            62,
  'Dennis Johnson':          62,
  'Glenn Robinson':          62,
  'Jerry Sloan':             62,
  'Joakim Noah':             62,
  'Khris Middleton':         62,
  'Mark Price':              62,
  'Pat Riley':               62,
  'Paul Westphal':           62,
  'Robert Horry':            62,
  'Sam Cassell':             62,
  'Sidney Moncrief':         62,
  'Stephon Marbury':         62,
  'Toni Kukoc':              62,
  'Tyrese Maxey':            62,
  'Vlade Divac':             62,
  'Calvin Murphy':           60,
  'Dan Majerle':             60,
  'Gordon Hayward':          60,
  'Jack Sikma':              60,
  'Jerry Lucas':             60,
  'Kristaps Porzingis':      65,
  'Lamar Odom':              60,
  'Mark Aguirre':            60,
  'Paolo Banchero':          60,
  'Spencer Haywood':         60,
  'Marques Johnson':         59,
  'Aaron Gordon':            58,
  'Allan Houston':           58,
  'Anthony Mason':           58,
  'Bill Bradley':            58,
  'Bob Dandridge':           58,
  'Byron Scott':             58,
  'Cade Cunningham':         58,
  'Danny Ainge':             58,
  'Danny Manning':           58,
  'Darius Garland':          58,
  'Derek Harper':            58,
  'George McGinnis':         58,
  'Hal Greer':               58,
  'John Starks':             58,
  'K.C. Jones':              58,
  'Luol Deng':               58,
  'Marcus Camby':            58,
  'Mike Bibby':              58,
  'Paul Silas':              58,
  'Ralph Sampson':           58,
  'Rudy Tomjanovich':        58,
  'Serge Ibaka':             58,
  'Steve Kerr':              58,
  'Terry Cummings':          58,
  'Tyler Herro':             58,
  'Tyson Chandler':          58,
  'Bob Love':                57,
  'Dejounte Murray':         57,
  'Detlef Schrempf':         57,
  'Evan Mobley':             57,
  'Jason Terry':             57,
  'Jeff Hornacek':           57,
  'Jerry Stackhouse':        57,
  'Julius Randle':           57,
  'Maurice Cheeks':          57,
  'Michael Redd':            57,
  'Nick Van Exel':           57,
  'Rolando Blackman':        57,
  'Tayshaun Prince':         57,
  'Tom Chambers':            57,
  'Tom Heinsohn':            57,
  'Carlos Boozer':           56,
  'Horace Grant':            56,
  'J.J. Redick':             78,
  'Jalen Green':             56,
  'Jamaal Wilkes':           56,
  'Michael Finley':          56,
  'Alvin Robertson':         55,
  'Andre Drummond':          55,
  'Boris Diaw':              55,
  'Brad Daugherty':          55,
  'Brook Lopez':             55,
  'Charlie Scott':           55,
  'Chet Holmgren':           55,
  'Deandre Ayton':           55,
  'Derek Fisher':            55,
  'Derrick Coleman':         55,
  'Derrick White':           55,
  'Doc Rivers':              55,
  'Doug Collins':            55,
  'Eddie Jones':             55,
  'Elton Brand':             55,
  'Fred VanVleet':           55,
  'Glen Rice':               55,
  'Goran Dragic':            55,
  'Gus Williams':            55,
  'J.R. Smith':              55,
  'Jamal Crawford':          55,
  'Jamal Mashburn':          55,
  'John Paxson':             55,
  'Lauri Markkanen':         55,
  'Marcus Smart':            55,
  'Mark Jackson':            55,
  'Michael Cooper':          55,
  'Monta Ellis':             55,
  'Nikola Vucevic':          55,
  'Norm Van Lier':           55,
  'Otis Thorpe':             55,
  'Reggie Lewis':            55,
  'Richard Jefferson':       55,
  'Sam Jones':               55,
  'Sean Elliott':            55,
  'Tobias Harris':           55,
  'Kenyon Martin':           54,
  'Brandon Ingram':          53,
  'RJ Barrett':              53,
  'Walter Davis':            53,
  'World B. Free':           53,
  'A.C. Green':              52,
  'Alvan Adams':             52,
  'Andrew Toney':            52,
  'Andrew Wiggins':          52,
  'Antawn Jamison':          52,
  'Antonio McDyess':         52,
  'Avery Johnson':           52,
  'B.J. Armstrong':          52,
  'Ben Gordon':              52,
  'Bobby Jones':             52,
  'Bruce Bowen':             52,
  'Charles Oakley':          52,
  'Chet Walker':             52,
  'Clint Capela':            52,
  'D\'Angelo Russell':       52,
  'Danny Green':             52,
  'Don Nelson':              52,
  'Doug Christie':           52,
  'Hedo Turkoglu':           52,
  'Jalen Williams':          52,
  'Jarrett Allen':           52,
  'Jason Richardson':        52,
  'Jo Jo White':             52,
  'Kiki Vandeweghe':         52,
  'Leandro Barbosa':         52,
  'Mahmoud Abdul-Rauf':      52,
  'Malcolm Brogdon':         52,
  'Mark Eaton':              52,
  'Maurice Lucas':           52,
  'Michael Porter Jr.':      52,
  'Mikal Bridges':           52,
  'Tristan Thompson':        52,
  'Vin Baker':               52,
  'Vinnie Johnson':          52,
  'Rashard Lewis':           51,
  'Terry Porter':            51,
  'Dick Van Arsdale':        50,
  'Eric Bledsoe':            50,
  'Eric Gordon':             50,
  'Franz Wagner':            50,
  'Fred Brown':              50,
  'Joe Ingles':              50,
  'Kirk Hinrich':            50,
  'Stephen Jackson':         50,
  'Austin Carr':             48,
  'Bailey Howell':           48,
  'Bobby Jackson':           48,
  'Bobby Portis':            48,
  'Cedric Ceballos':         48,
  'Chuck Person':            48,
  'Dale Ellis':              48,
  'Darrell Griffith':        48,
  'Duncan Robinson':         48,
  'Guy Rodgers':             48,
  'Kendall Gill':            48,
  'Larry Nance':             48,
  'Lionel Hollins':          48,
  'Luis Scola':              48,
  'Mehmet Okur':             48,
  'Mike Mitchell':           48,
  'Nate Robinson':           48,
  'P.J. Tucker':             48,
  'Robert Covington':        48,
  'Ty Lawson':               48,
  'Zydrunas Ilgauskas':      48,
  'Joe Barry Carroll':       47,
  'Kerry Kittles':           47,
  'Quentin Richardson':      47,
  'Danilo Gallinari':        46,
  'Derrick Favors':          46,
  'Rick Mahorn':             46,
  'Ryan Anderson':           46,
  'Walt Hazzard':            46,
  'David Lee':               45,
  'Desmond Mason':           45,
  'Fat Lever':               45,
  'John Salley':             45,
  'Kendrick Perkins':        55,
  'Larry Kenon':             45,
  'Sarunas Marciulionis':    45,
  'Taj Gibson':              45,
  'Terry Rozier':            45,
  'Bob Boozer':              44,
  'Brian Grant':             44,
  'Cole Anthony':            44,
  'Dario Saric':             44,
  'Dee Brown':               44,
  'Earl Boykins':            44,
  'Jae Crowder':             44,
  'Jalen Duren':             44,
  'Jordan Poole':            60,
  'Kenneth Faried':          44,
  'Matt Harpring':           44,
  'Nick Anderson':           44,
  'Patty Mills':             65,
  'Purvis Short':            44,
  'Raymond Felton':          44,
  'Reggie Jackson':          44,
  'Rick Fox':                44,
  'Shaun Livingston':        44,
  'Truck Robinson':          44,
  'Udonis Haslem':           44,
  'Wayne Embry':             44,
  'David West':              43,
  'Dennis Scott':            43,
  'Iman Shumpert':           43,
  'Kevin Porter':            43,
  'Mario Chalmers':          43,
  'Sherman Douglas':         43,
  'Spencer Dinwiddie':       43,
  'Tom Meschery':            43,
  'Al Harrington':           42,
  'Alperen Sengun':          42,
  'Andres Nocioni':          42,
  'Arron Afflalo':           42,
  'Bill Cartwright':         42,
  'Campy Russell':           42,
  'Chris Andersen':          42,
  'Clarence Weatherspoon':   42,
  'Dick Barnett':            42,
  'James Donaldson':         42,
  'James Silas':             42,
  'Jason Collins':           42,
  'JaVale McGee':            42,
  'Jim Jackson':             42,
  'Jon McGlocklin':          42,
  'Kurt Rambis':             42,
  'Larry Hughes':            42,
  'Lu Dort':                 42,
  'Marcus Morris':           42,
  'Max Strus':               42,
  'Mike Dunleavy Jr.':       42,
  'Nate McMillan':           42,
  'Nene':                    42,
  'P.J. Brown':              42,
  'Paul Pressey':            42,
  'Phil Smith':              42,
  'Rafer Alston':            42,
  'Rudy LaRusso':            42,
  'Sharone Wright':          42,
  'Tyrone Hill':             42,
  'Vinny Del Negro':         42,
  'Austin Reaves':           41,
  'Billy Owens':             41,
  'Bob Rule':                41,
  'Brian Shaw':              41,
  'Clifford Ray':            41,
  'Drew Gooden':             41,
  'Greg Ostertag':           41,
  'Happy Hairston':          41,
  'James Posey':             41,
  'LaPhonso Ellis':          41,
  'Lindsey Hunter':          41,
  'Mike Miller':             41,
  'P.J. Washington':         41,
  'Robert Reid':             41,
  'Samuel Dalembert':        41,
  'Scott Wedman':            41,
  'Tiago Splitter':          41,
  'Antoine Carr':            40,
  'Bob Gross':               40,
  'Butch Beard':             40,
  'Chris Duhon':             40,
  'Craig Ehlo':              40,
  'Dante Exum':              40,
  'Dave Twardzik':           40,
  'Don Kojis':               40,
  'Eddie House':             40,
  'Eddy Curry':              40,
  'Eric Snow':               40,
  'Gabe Vincent':            40,
  'Jabari Smith Jr.':        40,
  'James Jones':             40,
  'Jim Chones':              40,
  'Larry Steele':            40,
  'Lonnie Shelton':          40,
  'M.L. Carr':               40,
  'Mickael Pietrus':         40,
  'Payton Pritchard':        40,
  'Rasho Nesterovic':        40,
  'Saddiq Bey':              40,
  'Scot Pollard':            40,
  'T.R. Dunn':               40,
  'Thurl Bailey':            40,
  'Voshon Lenard':           40,
  'Clint Richardson':        39,
  'Eric Maynor':             39,
  'Len Chappell':            39,
  'Luc Longley':             39,
  'Aaron Williams':          38,
  'Adonal Foyle':            38,
  'Blair Rasmussen':         38,
  'Charles Dudley':          38,
  'Charles Johnson':         38,
  'Charlie Ward':            38,
  'Christian Braun':         38,
  'Chuck Hayes':             38,
  'Danny Ferry':             38,
  'David Benoit':            38,
  'Frank Johnson':           38,
  'Franklin Edwards':        38,
  'George Johnson':          38,
  'Jaxson Hayes':            38,
  'Johnny Egan':             38,
  'Keith Bogans':            38,
  'Kevon Looney':            38,
  'Terry Mills':             38,
  'Wali Jones':              38,
  'Art Williams':            37,
  'Leon Powe':               37,
  'Dave Corzine':            36,
  'Don Ford':                36,
  'Luke Jackson':            36,
  'Luol McCarter':           36,
  'Norris Cole':             36,
  'Gabriel Hatcher':         35,
};

// ─── Stat-based fallback ──────────────────────────────────────────────────────
function formulaPopularity(player) {
  // Base from scoring — most recognisable stat in the public eye
  const ppgBase = Math.min(player.ppg / 35, 1) * 55; // 35 ppg → 55 pts

  // Supporting stats add a little
  const supportBase =
    (player.apg / 12) * 8 +   // elite PG-level assists
    (player.rpg / 20) * 7 +   // elite rebounder
    (player.spg / 3)  * 5 +
    (player.bpg / 5)  * 5;

  const base = Math.round(ppgBase + supportBase);

  // Deterministic jitter from the player id so the same player always
  // gets the same score (no randomness).
  let hash = 0;
  for (let i = 0; i < (player.id || player.name).length; i++) {
    hash = ((hash << 5) - hash) + (player.id || player.name).charCodeAt(i);
    hash |= 0;
  }
  const jitter = Math.abs(hash % 11) - 5; // -5 … +5

  return Math.min(100, Math.max(35, base + jitter));
}

// ─── Apply ────────────────────────────────────────────────────────────────────
let total = 0, named = 0, formula = 0;

for (const key of Object.keys(db)) {
  for (const player of db[key]) {
    if (NAMED[player.name] !== undefined) {
      player.popularity = NAMED[player.name];
      named++;
    } else {
      player.popularity = formulaPopularity(player);
      formula++;
    }
    total++;
  }
}

fs.writeFileSync(SRC, JSON.stringify(db, null, 2), 'utf8');

console.log(`Done.`);
console.log(`  Total players     : ${total}`);
console.log(`  Named overrides   : ${named}`);
console.log(`  Formula-derived   : ${formula}`);
console.log(`Wrote ${SRC}`);
